
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("BoostSnapshot")
export class BoostSnapshot extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Required
	@Column("Boolean")
	blueprint: Boolean

	@Required
	@Column("Boolean")
	dinero: Boolean

	@Required
	@Column("Boolean")
	hyperliquid: Boolean
  constructor(data: Partial<BoostSnapshot>) {super()}
}


const source = `type BoostSnapshot @entity {
  id: String!
  blueprint: Boolean!
  dinero: Boolean!
  hyperliquid: Boolean!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "BoostSnapshot": BoostSnapshot
  }
})
